inveniosoftware/flask-iiif

- flask_iiif/__init__.py
- flask_iiif/errors.py
- flask_iiif/restful.py
- setup.py
* FIX pep257 issues.
* FIX python 2.6 compatibility
> flask_iiif: python compatibility and fixes

- .gitignore
- flask_iiif/__init__.py
- flask_iiif/utils.py
- tests/test_context_template.py
* Improves PEP8 syntax.
* NEW Adds `iiif_image_url` context function template.
> flask_iiif: iiif url context template

- RELEASE-NOTES.rst
* Uses new standard greeting phrase.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> docs: "happy hacking" instead of "good luck"

- flask_iiif/__init__.py
- flask_iiif/api.py
- flask_iiif/config.py
- flask_iiif/decorators.py
- flask_iiif/errors.py
- flask_iiif/restful.py
- flask_iiif/signals.py
- setup.py
- tests/helpers.py
- tests/test_context_template.py
- tests/test_ext.py
- tests/test_image_simple_cache.py
- tests/test_multimedia_image_api.py
- tests/test_restful_api.py
- tests/test_restful_api_signals.py
* NEW adds signals in the restful api.
* NEW adds a configurable decorator to the api.
> flask_iiif: iiif signals and decorators

- .travis.yml
> global: fix travis building issues

- AUTHORS
- docs/index.rst
- flask_iiif/api.py
- flask_iiif/cache/cache.py
- flask_iiif/cache/simple.py
- flask_iiif/config.py
- flask_iiif/restful.py
* Minor documentation updates to clean the language.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
Reviewed-by: Harris Tzovanakis <me@drjova.com>
> global: documentation updates

- CHANGES
- RELEASE-NOTES.rst
- flask_iiif/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
Reviewed-by: Harris Tzovanakis <me@drjova.com>
> Flask-IIIF v0.2.0

- .travis.yml
- docs/conf.py
- flask_iiif/__init__.py
- flask_iiif/api.py
- flask_iiif/cache/cache.py
- flask_iiif/cache/simple.py
- flask_iiif/errors.py
- flask_iiif/restful.py
- pytest.ini
- run-tests.sh
- setup.py
> global: fix failing tests with Pillow 3.0

- .lgtm
- MAINTAINERS
- MANIFEST.in
- README.rst
- RELEASE-NOTES.rst
- docs/conf.py
- docs/index.rst
- setup.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
> global: initial MAINTAINERS list

- MANIFEST.in
- docs/requirements.txt
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> docs: move to readthedocs.io

- .travis.yml
- flask_iiif/restful.py
- flask_iiif/signals.py
- tests/test_restful_api_signals.py
* NEW Adds signal before IIIFImageInfo get request.
Signed-off-by: Øystein Blixhavn <oystein@blixhavn.no>
> signals: addition of signal before info request

- RELEASE-NOTES.rst
- flask_iiif/version.py
> release: v0.2.1

- flask_iiif/api.py
- setup.py
> setup: update pillow version

- .travis.yml
- docs/index.rst
- flask_iiif/__init__.py
- flask_iiif/cache/cache.py
- flask_iiif/cache/redis.py
- flask_iiif/config.py
- setup.py
- tests/test_image_redis_cache.py
- NEW Adds wrapper for Redis using werkzeug's RedisCache and redis-py.
- FIX Fixes cache handler loading from config.
Signed-off-by: Alexander Ioannidis a.ioannidis@cern.ch
> cache: addition of Redis

- CHANGES
- RELEASE-NOTES.rst
- flask_iiif/api.py
- flask_iiif/restful.py
- flask_iiif/version.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> release: v0.3.0

- flask_iiif/__init__.py
Fixes isort issue causing the travis build to fail.
(Closes #56)
> fix isort issue

- docs/conf.py
- flask_iiif/cache/cache.py
- flask_iiif/cache/redis.py
- flask_iiif/cache/simple.py
- flask_iiif/restful.py
- flask_iiif/utils.py
- tests/helpers.py
- tests/test_restful_api.py
> restful: Add Last-Modified and If-Modified-Since to imageAPI headers.

- flask_iiif/decorators.py
- flask_iiif/restful.py
> global: remove warning message for LocalProxy

- CHANGES
- flask_iiif/api.py
- flask_iiif/version.py
> api: fix werkzeug deprecation warning

- .travis.yml
- CHANGES
- flask_iiif/__init__.py
- flask_iiif/cache/cache.py
- flask_iiif/cache/redis.py
- flask_iiif/cache/simple.py
- flask_iiif/config.py
- flask_iiif/restful.py
- flask_iiif/version.py
- tests/helpers.py
- tests/test_restful_api.py
it is currently breaking other modules (f.e invenio-iiif) because of werkzeug imports
> Drop support for python 2.7 and release
